Repository UnofficialCrusaderPatch/UnofficialCrusaderPatch, pull requests merged in 2021-02, with the labels that each got.

#759 Changing the AIC Updater and the Project to contain these new AIC nam…
  AICUpdater/AICUpdaterHelper.cs
  UnofficialCrusaderPatch/AIC/Utils/AICHelper.cs
  UnofficialCrusaderPatch/AIC/Utils/AIPersonality.cs
  UnofficialCrusaderPatch/AIC/Utils/AIPersonalityFieldsEnum.cs
  UnofficialCrusaderPatch/AIC/Utils/AISerializer.cs
Labels: Needs comment by tester

#733 Customize AI initial defence recruit time
  UnofficialCrusaderPatch/CodeBlocks/ai_recruitstate_initialtimer.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester

#725 Add seed modification possibility
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility.block
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility_fn1.block
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility_fn2.block
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility_fn3.block
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility_fn4.block
  UnofficialCrusaderPatch/CodeBlocks/o_seed_modification_possibility_fn5.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/Patching/Patcher.cs
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Tested with SHC, Tested with SHC-E

#742 [doc] Update CI
  .github/workflows/dotnet-core-desktop.yml
Labels: Awaiting merge
