Repository UnofficialCrusaderPatch/UnofficialCrusaderPatch, pull requests merged in 2021-08, with the labels that each got.

#737 Add fix for rapid deletion bug
  UnofficialCrusaderPatch/CodeBlocks/o_fix_rapid_deletion_bug.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Awaiting merge

#865 Minor FIX №2 15.07.2021
  UnofficialCrusaderPatch/Localization/Russian.txt
Labels: Needs comment by tester

#872 Arabic translation for the UCP
  UnofficialCrusaderPatch/Localization/Arabic.txt
  UnofficialCrusaderPatch/Localization/Localization.cs
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  resources/aic/Kimberly-Balance-v1.5.json
  resources/aic/Krarilotus-aggressiveAI-v1.3.json
  resources/aic/UCP-AI-Patch.json
  resources/aic/Xander10alpha_Enhanced_Vanilla_AI_1.1.json
  resources/aic/vanilla.json
  resources/aiv/EvreyFixed/Arabic.txt
  resources/aiv/EvreyHistory/Arabic.txt
  resources/aiv/EvreyImproved/Arabic.txt
  resources/aiv/PitchSiege/Arabic.txt
  resources/aiv/PitchWells/Arabic.txt
  resources/aiv/Tatha/Arabic.txt
  resources/goods/vanilla.json
  resources/troops/UCP-StartingTroops-Patch.json
  resources/troops/vanilla.json
Labels: Awaiting merge

#871 Disable extreme bar network function
  UnofficialCrusaderPatch/CodeBlocks/o_xtreme_bar3.block
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#870 Fix map sending problem
  UnofficialCrusaderPatch/CodeBlocks/o_fix_map_sending.block
  UnofficialCrusaderPatch/Localization/Arabic.txt
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#777 disable border scrolling
  UnofficialCrusaderPatch/CodeBlocks/o_disable_border_scrolling.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#772 Separate wasd and quicksave feature
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#768 added jester doesnt move to assassins on the battlefield fix
  UnofficialCrusaderPatch/CodeBlocks/u_jestermoveto_assassin.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#751 Place killing pits like pitch ditches
  UnofficialCrusaderPatch/CodeBlocks/o_fast_placing.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by author, Needs comment by tester, awaiting premature merge

#746 Allow changing gamespeed with non-numpad keys
  UnofficialCrusaderPatch/CodeBlocks/o_gamespeednumkey.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#735 Added remove right click context menu option
  UnofficialCrusaderPatch/CodeBlocks/o_remove_right_click_context_menu.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by tester, awaiting premature merge

#688 Added Restore AI Siege messages
  UnofficialCrusaderPatch/CodeBlocks/ai_restore_ai_siege_messages.block
  UnofficialCrusaderPatch/CodeBlocks/ai_restore_ai_siege_messages_data1.block
  UnofficialCrusaderPatch/CodeBlocks/ai_restore_ai_siege_messages_data2.block
  UnofficialCrusaderPatch/CodeBlocks/ai_restore_ai_siege_messages_data3.block
  UnofficialCrusaderPatch/CodeBlocks/ai_restore_ai_siege_messages_data4.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by author, awaiting premature merge

#658 Fix engineers not dying when siege engine they are manning is killed
  UnofficialCrusaderPatch/AIC/AICChange.cs
  UnofficialCrusaderPatch/CodeBlocks/u_ghostengineer.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by author, Needs comment by tester, awaiting premature merge

#634 Fix assassin pathing and behaviour
  UnofficialCrusaderPatch/CodeBlocks/u_assassinfix_descension.block
  UnofficialCrusaderPatch/CodeBlocks/u_assassinfix_forgetfullness.block
  UnofficialCrusaderPatch/CodeBlocks/u_assassinfix_forgetfullness_wall_climb.block
  UnofficialCrusaderPatch/Localization/Chinese.txt
  UnofficialCrusaderPatch/Localization/English.txt
  UnofficialCrusaderPatch/Localization/German.txt
  UnofficialCrusaderPatch/Localization/Hungarian.txt
  UnofficialCrusaderPatch/Localization/Polish.txt
  UnofficialCrusaderPatch/Localization/Russian.txt
  UnofficialCrusaderPatch/UnofficialCrusaderPatch.csproj
  UnofficialCrusaderPatch/Version.cs
Labels: Needs comment by author, awaiting premature merge
